version: "2"

networks:
  udaconnect-net:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - udaconnect-net

  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - udaconnect-net
  udaconnect_locations_api:
    image: '84black84/udaconnect_locations_api:latest'
    networks:
      - udaconnect-net
  udaconnect_locations_producer:
    image: '84black84/udaconnect_locations_producer:latest'
    networks:
      - udaconnect-net